version: '3.3'
services:

  app:
    container_name: challenge-full-stack-web-app
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    expose:
      - "8080"
    ports:
      - 8080:8080
    command: "npm install && npm run serve"
    depends_on:
      - api

  api:
    container_name: challenge-full-stack-web-api
    image: "node:12"
    user: "node"
    working_dir: /home/node/api
    volumes:
      - ./api:/home/node/api
    expose:
      - "3000"
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    command: "npm install && npm start"
    depends_on:
      - db

  db:
    container_name: challenge-full-stack-web-db
    image: mysql:8.0.21
    volumes:
      - .data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'challenge-full-stack-web-db'